#!/bin/bash

this_dir="$(realpath $(dirname $0))"
mkdir -p ~/.config

function ln_dir_contents() {
    src_dir="$1"
    dest_dir="$2"
    for fname in "$src_dir"/* "$src_dir"/.*; do
        base="$(basename $fname)"
        if [ "$base" = . -o "$base" = .. ]; then
            continue
        fi
        echo ln -sf "$fname" "$dest_dir/$(basename $fname)"
        ln -sf "$fname" "$dest_dir/$(basename $fname)"
    done
}

ln_dir_contents "$this_dir/home" "$HOME"
ln_dir_contents "$this_dir/.config" "$HOME/.config"
