#!/bin/bash

this_dir="$(realpath $(dirname $0))"
mkdir -p ~/.config
# we only track a couple files in the nvim directory, because that's also where
# Plug (the package manager) installs stuff.
mkdir -p ~/.config/nvim

function ln_dir_contents() {
    src_dir="$1"
    dest_dir="$2"
    for fname in "$src_dir"/* "$src_dir"/.*; do
        base="$(basename $fname)"
        if [ "$base" = . -o "$base" = ..  -o "$base" = "*" ]; then
            continue
        fi
        echo ln -sfn "$fname" "$dest_dir/$(basename $fname)"
        ln -sfn "$fname" "$dest_dir/$(basename $fname)"
    done
}

ln_dir_contents "$this_dir/home" "$HOME"
ln_dir_contents "$this_dir/.config" "$HOME/.config"
ln_dir_contents "$this_dir/nvim" "$HOME/.config/nvim"
